apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubekit-prepare
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubekit-prepare
  namespace: default
rules:
  # for validation service account exists
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - get
  # for aggregate target service account rules
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - roles
    verbs:
      - get
      - list
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - clusterrolebindings
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubekit-prepare-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubekit-prepare
subjects:
  - kind: ServiceAccount
    name: kubekit-prepare
    namespace: default
